apiVersion: v1
data:
  bookmarks.yaml: |
    - Repositories:
      - GitHub:
        - abbr: GH
          icon: github.png
          href: https://github.com/pontusc
          description: Profile

      - Homelab:
        - abbr: HL
          icon: github.png
          href: https://github.com/pontusc/homelab
          description: Config

      - Homepage:
        - abbr: HP
          icon: github.png
          href: https://github.com/pontusc/homepage
          description: Config

      - Dotfiles:
        - abbr: DF
          icon: github.png
          href: https://github.com/pontusc/.dotfiles
          description: Config

      - Neovim:
        - abbr: NVim
          icon: github.png
          href: https://github.com/pontusc/nvim
          description: Config

      - Rekurrens:
        - abbr: GL
          icon: gitlab.png
          href: https://git.chasacademy.dev/chas-challenge-2025/group-12/rekurrens
          description: CC
  custom.css: ""
  custom.js: ""
  docker.yaml: ""
  kubernetes.yaml: |
    ingress: true
    traefik: true
    mode: cluster
  services.yaml: |
    - Cluster Management:
      - Traefik:
          href: https://traefik.nejlikka.com
          siteMonitor: http://traefik.kube-system.svc.cluster.local:8080
          icon: traefik.png
          description: Ingress
          widget:
            type: traefik
            url: http://traefik.kube-system.svc.cluster.local:8080

      - Prometheus:
          href: https://prometheus.nejlikka.com
          siteMonitor: http://prometheus-server.monitoring.svc.cluster.local
          icon: prometheus.png
          description: Cluster logs
          widget:
            type: prometheus
            url: http://prometheus-server.monitoring.svc.cluster.local

      - ArgoCD:
          href: https://argocd.nejlikka.com
          siteMonitor: http://argocd-server.argocd.svc.cluster.local:80
          icon: argo-cd.png
          description: Kubernetes GitOps
          widget:
            type: argocd
            url: http://argocd-server.argocd.svc.cluster.local:80
            key: "{{HOMEPAGE_VAR_ARGO_API_KEY}}"

      - Grafana:
          href: https://grafana.nejlikka.com
          siteMonitor: http://grafana.monitoring.svc.cluster.local
          icon: grafana.png
          description: Reports & Alerts
          widget:
            type: grafana
            url: http://grafana.monitoring.svc.cluster.local
            username: homepage_user
            password: "{{HOMEPAGE_VAR_GRAFANA_PASSWORD}}"

      - Authentik:
          href: https://authentik.nejlikka.com
          siteMonitor: http://authentik-server.authentik.svc.cluster.local
          icon: authentik.png
          description: Authentication
          widget:
            type: authentik
            url: http://authentik-server.authentik.svc.cluster.local
            key: "{{HOMEPAGE_VAR_AUTHENTIK_API_KEY}}"

      - Uptime-kuma:
          href: https:///kuma.nejlikka.com
          siteMonitor: http://uptime-kuma.monitoring.svc.cluster.local:3001
          icon: uptime-kuma.png
          description: Service monitoring
          widget:
            type: uptimekuma
            url: http://uptime-kuma.monitoring.svc.cluster.local:3001
            slug: services

      - Longhorn:
          href: https://longhorn.nejlikka.com
          siteMonitor: http://longhorn-frontend.longhorn-system.svc.cluster.local
          icon: longhorn.png
          description: CSI Provider

      - Rancher:
          href: https://rancher.nejlikka.com
          siteMonitor: https://rancher.nejlikka.com
          icon: rancher.png
          description: Kubernetes management
  settings.yaml: |
    description: Homelab
    title: Homelab
    background: https://w.wallhaven.cc/full/d6/wallhaven-d6j79o.png
    statusStyle: "dot"
    cardBlur: md
    theme: dark
    language: en
    disableCollapse: true
    color: slate

    layout:
      Cluster Management:
        icon: kubernetes.png
        useEqualHeights: true
        style: row
        columns: 2
      Deployments:
        style: row
        columns: 4
      Repositories:
        style: row
        columns: 6
        useEqualHeights: true
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: false
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: false
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        disk: /
        cpu: true
        memory: true
        uptime: true
        network: false
    # - longhorn:
    #     expanded: true
    #     total: true
    #     labels: true
    #     nodes: false

    - openmeteo:
        label: Stockholm # optional
        latitude: 59.3377
        longitude: 18.0900
        timezone: Europe/Stockholm # optional
        units: metric # or imperial
        cache: 5 # Time in minutes to cache API responses, to stay within limits
        format: # optional, Intl.NumberFormat options
          maximumFractionDigits: 1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: homepage-config
