apiVersion: v1
kind: Namespace
metadata:
  name: teamspeak

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teamspeak-pvc
  namespace: teamspeak
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 256Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teamspeak-deployment
  namespace: teamspeak
  labels:
    app: teamspeak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teamspeak
  template:
    metadata:
      namespace: teamspeak
      labels:
        app: teamspeak
    spec:
      containers:
      - name: teamspeak-server
        image: teamspeak:3.13.7
        ports:
        - name: voice
          containerPort: 9987
          protocol: UDP
        - name: file-transfer
          containerPort: 30033
        - name: server-query
          containerPort: 10011
        resources:
        env:
        - name: TS3SERVER_LICENSE
          value: accept
        volumeMounts:
        - mountPath: /var/ts3server/
          name: teamspeak-data
      volumes:
      - name: teamspeak-data
        persistentVolumeClaim:
          claimName: teamspeak-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: teamspeak-service
  namespace: teamspeak
  labels:
    app: teamspeak
spec:
  ports:
  - port: 9987
    targetPort: voice
    protocol: UDP
    name: voice
  - port: 30033
    targetPort: file-transfer
    name: file-transfer
  - port: 10011
    targetPort: server-query
    name: server-query
  selector:
    app: teamspeak

---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: teamspeak-filetransfer
  namespace: teamspeak
spec:
  entryPoints:
  - ts-filetransfer
  routes:
  - match: HostSNI(`*`)
    # - match: HostSNI(`ts.nejlikka.com`)
    services:
    - name: teamspeak-service
      port: file-transfer

---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: teamspeak-serverquery
  namespace: teamspeak
spec:
  entryPoints:
  - ts-serverquery
  routes:
  - match: HostSNI(`*`)
    # - match: HostSNI(`ts.nejlikka.com`)
    services:
    - name: teamspeak-service
      port: server-query

---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: teamspeak-voice
  namespace: teamspeak
spec:
  entryPoints:
  - ts-voice
  routes:
  - services:
    - name: teamspeak-service
      port: voice
