apiVersion: v1
kind: Namespace
metadata:
  name: teamspeak

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teamspeak-pvc
  namespace: teamspeak
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 256Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teamspeak-deployment
  namespace: teamspeak
  labels:
    app: teamspeak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teamspeak
  template:
    metadata:
      namespace: teamspeak
      labels:
        app: teamspeak
    spec:
      containers:
      - name: teamspeak-server
        image: teamspeak:3.13.7
        ports:
        - name: voice
          containerPort: 9987
          protocol: UDP
        - name: file-transfer
          containerPort: 30033
        - name: server-query
          containerPort: 10011
        resources:
        env:
        - name: TS3SERVER_LICENSE
          value: accept
        volumeMounts:
        - mountPath: /var/ts3server/
          name: teamspeak-data
      volumes:
      - name: teamspeak-data
        persistentVolumeClaim:
          claimName: teamspeak-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: teamspeak-service
  namespace: teamspeak
  labels:
    app: teamspeak
spec:
  ports:
  - port: 9987
    targetPort: voice
    protocol: UDP
    name: voice
  - port: 30033
    targetPort: file-transfer
    name: file-transfer
  - port: 10011
    targetPort: server-query
    name: server-query
  selector:
    app: teamspeak

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: teamspeak-tcp
  namespace: teamspeak
spec:
  rules:
  - host: example.foo.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service1
            port:
              number: 80
---

---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: teamspeak-udp
  namespace: teamspeak
spec:
  entryPoints:
  - teamspeak
  routes:
  - services:
    - name: teamspeak-service
      port: ts
