---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBEUDlOGaalR2xBeqJumwDbdtYT5ySQD9KdWq8N1Ey7i+ii0gl6AF1WrXgI6MYEIzAAKHmO6aXo4ufGQU5XPDdyl/cceJWbVxMok8/wP8NPYwv/Spk+eR0XaUPd9WrNDXVh/3hDFxyKk9rlp2Qz7I1fW5RKpdvEXKhxJusE9Y3YeY9cpIbYS5o7Q9KU+vpZCDVemrEVz08vIMxwHV2rmGVV/IQHxhMMSRYevxhOLjEkkSWQqXHDhbyuI9l8jTC/1Y8XYByBLcnjUeKJw5m3zPDLZbgJkoDaOTzR2VVKR2Si8axMNRXNeAnPMMO6gD1cFbHer/yP+FtnWpian9iWAnQ4icZ/ZeuuMxMHUZonCi6IaxRVljlshefODgVY+LBhc4zZgZjv9XJLDMquNJSpr3s/QE8SdIIkVTVpUDS0jiQGpKvwzaVNWQvMLinfz2GgaA2DurQutMEHBtXol0o2yW1W8lHsh8r+W1NFvBBDu34YTnhguQKLwODEzjCMBQCN1y1CfZn0g80u9hcfJjKd2uuwdN+cSKMcef/2SfTae52LTov9gS3B7IuKU/OoGEA/zlodpAH1BPMVQwBhTKaY5oVveQN3UvXGD7ktEjbYrm90n/6cR8cr4H+QV181FNojKswmVqRsTeMuL4/LzTVDlatRJw1LaLLVhQnxWQwloWgqEsF/g9ifae8J0X+ixxzUN4wiSRnpKk9K+wkKt9vVELoz86l9DfvfiDb1fk3zcYLQAQBgFfdOrX97
    admin-user: AgAmlbYVWImhCGUoe9Od5RJYrAoHI8S4gpUOfRZgdaSqaO1c5ABXWxSBPTOXxe++ziL5vHeWTj7e9Yep6rHfuRVGdx8iEVRSClN1Ci1IfZjPFtVWXkAXGJcKPaUum5KpK1TXyalw2TBbUtL52sJ1zntkoziGkCwGV2vTqPKNyJGcr8EMhz5jXDJc1wWxOCFWgCS2SajvgYJH6U8t1l0jMJTt4sU06Py5QSA0577ZRsF7T0eMisu+UekzTVqTO50YBNh6YH3BLikYQqUvrr9A58m0M6wZo2IRQmVM6QKwpGDfgEw038vWw8/rUmKzuVC/x5t3gXNkf0QtDeE04RYeRsdEoZ7CzTqeCFdyHLAKeCbgvAPZp9OwYds/WzYGQQ9tZo3+Vp7hC1wymoHz7/hsMikdkLdy4ddsdjag5W4GoyPizuEGAdPkx/1IRCPr7BVPyABzWP1hiigw9GAcoSAtDrUUIJYrDdEo3sGKGczxtvR5ERol4m757qcwqCqYssnAmky3FTprEexLfJaQXa8b+fQYLiczIn/1j/zfC1GOi0Daleqo2JqXMJM21CGz5P83nYxKIoFygElOr9zTtL+6RjFWRcDZPy6v1mbTOTrKB1DzMpfYe6Zj+tGcg9fH+Ik/4Y45/Po85i6TAirhhTO5020es8JmiELmkB1mZ0seQYn8V+h055gQU2BfBcHakAr1zzQeqttmhw==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: monitoring
    type: Opaque
