apiVersion: v1
kind: Namespace
metadata:
  name: traefik

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
  namespace: traefik
spec:
  redirectScheme:
    scheme: https
    # Port has to be a string
    # port: "443"
    permanent: true
