apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - "--api"
      - "--api.dashboard=true"
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
    ingressRoute:
      dashboard:
        enabled: true
        matchRule: Host(`traefik.local.nejlikka.com`)
        annotations:
          # Below are for automatic homepage discovery, decided to specify in homepage file instead
          # gethomepage.dev/description: Traefik dashboard
          # gethomepage.dev/href: "https://traefik.local.nejlikka.com/dashboard/#/"
          # gethomepage.dev/name: Traefik
          # gethomepage.dev/enabled: "true"
          # gethomepage.dev/group: Cluster Management
          # gethomepage.dev/icon: traefik.png
          # gethomepage.dev/pod-selector: app.kubernetes.io/name=traefik
        entryPoints:
          - websecure
        # middlewares: authentik-ak-outpost-authentik-embedded-outpost@kubernetescrd
    ports:
      web:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true
    tlsStore:
      default:
        defaultCertificate:
          secretName: wildcard-default-cert
    logs:
      access:
        enabled: true
