apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - "--api=true"
      - "--api.dashboard=true"
      - "--api.disabledashboardad=true"
      - "--api.insecure=true"
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
    ingressRoute:
      dashboard:
        enabled: true
        matchRule: Host(`traefik.nejlikka.com`)
        entryPoints:
          - websecure
        middlewares:
          - name: authentik-ak-outpost-authentik-embedded-outpost@kubernetescrd
    ports:
      websecure:
        port: 443
      web:
        port: 80
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true
      traefik:
        expose:
          default: true
      teamspeak:
        port: 9987
        exposedPort: 9987
        protocol: UDP
        expose:
          default: true
    tlsStore:
      default:
        defaultCertificate:
          secretName: wildcard-default-cert
    logs:
      access:
        enabled: true
