apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - "--api=true"
      - "--api.dashboard=true"
      - "--api.disabledashboardad=true"
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
    ingressRoute:
      dashboard:
        enabled: true
        matchRule: Host(`traefik.local.nejlikka.com`)
        entryPoints:
          - websecure
        middlewares:
          - name: authentik-ak-outpost-authentik-embedded-outpost@kubernetescrd
    ports:
      web:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true
    tlsStore:
      default:
        defaultCertificate:
          secretName: wildcard-default-cert
    logs:
      access:
        enabled: true
