apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aboutme
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    gethomepage.dev/name: About me
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Deployments
    gethomepage.dev/icon: nginx.png
    gethomepage.dev/pod-selector: app=aboutme
spec:
  ingressClassName: traefik
  rules:
  - host: aboutme.nejlikka.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: aboutme
            port:
              number: 80

---
apiVersion: v1
kind: Service
metadata:
  name: aboutme
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: aboutme

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aboutme
spec:
  selector:
    matchLabels:
      app: aboutme
  replicas: 3
  template:
    metadata:
      labels:
        app: aboutme
    spec:
      containers:
      - name: aboutme
        image: pontusc/aboutme:1749319988
        ports:
        - containerPort: 80
