apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-le-issuer
  namespace: cert-manager
spec:
  acme:
    email: pontuscurtsson@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cloudflare-le-issuer-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: api-token-cloudflare
              key: api-token
