services:
  ddclient:
    image: lscr.io/linuxserver/ddclient:4.0.0
    container_name: ddclient
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Europe/Stockholm
    volumes:
    - /home/pontusc/homelab/ddns/config:/config
    restart: unless-stopped
