- kubernetes:
    cluster:
      show: false
      cpu: true
      memory: true
      showLabel: true
      label: "cluster"
    nodes:
      show: false
      cpu: true
      memory: true
      showLabel: true
- resources:
    backend: resources
    expanded: true
    disk: /
    cpu: true
    memory: true
    uptime: true
    network: default
# - longhorn:
#     expanded: true
#     total: true
#     labels: true
#     nodes: true
- search:
    provider: duckduckgo
    target: _blank
