- kubernetes:
    cluster:
      show: false
      cpu: true
      memory: true
      showLabel: true
      label: "cluster"
    nodes:
      show: false
      cpu: true
      memory: true
      showLabel: true
- resources:
    backend: resources
    expanded: true
    disk: /
    cpu: true
    memory: true
    uptime: true
    network: default
# - longhorn:
#     expanded: true
#     total: true
#     labels: true
#     nodes: true
- search:
    provider: google
    target: _blank

- openweathermap:
    label: Stockholm
    latitude: 59.3377
    longitude: 18.0900
    units: metric # or imperial
    provider: openweathermap
    cache: 10 # Time in minutes to cache API responses, to stay within limits
    format: # optional, Intl.NumberFormat options
      maximumFractionDigits: 1
